retail_transformation:
  outputs:
    dev:
      account: KCWRAED-YY61203
      database: RETAIL_ANALYTICS_DB
      password: Mohitdjbravo@007
      role: SYSADMIN
      schema: ANALYTICS_REPORTING
      threads: 1
      type: snowflake
      user: Mohitverma777
      warehouse: COMPUTE_WH
  target: dev
