retail_transformation:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'RETAIL_ANALYTICS_DB') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'RAW_STAGING') }}"
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:"{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
  target: dev
