retail_transformation:
  outputs:
    dev:
      account: account
      database: db_name
      password: pass
      role: role
      schema: schema
      threads: 1
      type: type
      user: user
      warehouse: warehouse
  target: dev
